### PR TITLE
Github Action - Publish python package

### PR DESCRIPTION
**Pull request by jakubno**

### CODE REVIEW

**Comment by ValentaTomas** [comment]
You even moved fastapi generator to dev deps, great.

Can you just add that the GH action is triggered on git tag (vX.Y.Z) and it then automatically creates the release with the tag name as the release version name when it successfully publishes the package?

I think we have GH action with the tag+release here for reference https://github.com/devbookhq/sdk/blob/master/.github/workflows/release.yml

**Comment by jakubno** [comment]
I am now just thinking, if we have all SDKs in one repo, do we want to keep the publishing/releases for all SDKs together? Shouldn't we distinguish it etc by some prefix/suffix in tag?

**Comment by ValentaTomas** [comment]
That's a good question. I think a counterargument could be that releases are "cheap" and that there is a value in the clarity of always having all SDKs on the same version so you don't have to keep track of how the multiple versions interact and if you really have the last one installed.

I think a good solution could be having the minor and major versions always released together and the patch version would be specific to each SDK?

It is worth mentioning tools for versioning packages inside monorepos like https://github.com/changesets/changesets and to think about monorepo management tools overall - because that's what this is.

We'll definitely need to think this through as we start adding more supported languages.

**Comment by mlejva** [comment]
I'm strongly in favor of having separate releases. Releasing all SDKs because we updated just one creates burden on users

**Comment by ValentaTomas** [comment]
I think we can have that with:
> I think a good solution could be having the minor and major versions always released together (because it does not make sense to have one SDK on a different non-patch version) and the patch version would be specific to each SDK?

We may move from the git tag releasing then though, because the having the list of releases (+ git tags) will be a mess if there are separate releases for each SDK in the list.

For the Python SDK we can have it as it is, but then we need to solve it.

I created a Linear issue from this - https://linear.app/e2b/issue/E2B-23/improve-sdk-monorepo-publishing.

**Pull request merged**
